ADD_TEST(compile_fail_bad_array_power "scripts/compile_fail" "bad/bad_array_power.ept" "-memalloc")
ADD_TEST(compile_fail_bad_flatten "scripts/compile_fail" "bad/bad_flatten.ept" "-memalloc")
ADD_TEST(compile_fail_bad_merge1 "scripts/compile_fail" "bad/bad_merge1.ept" "-memalloc")
ADD_TEST(compile_fail_bad_merge2 "scripts/compile_fail" "bad/bad_merge2.ept" "-memalloc")
ADD_TEST(compile_fail_bad_merge3 "scripts/compile_fail" "bad/bad_merge3.ept" "-memalloc")
ADD_TEST(compile_fail_bad_param_ident "scripts/compile_fail" "bad/bad_param_ident.ept" "-memalloc")
ADD_TEST(compile_fail_causality "scripts/compile_fail" "bad/causality.ept" "-memalloc")
ADD_TEST(compile_fail_clock_annot "scripts/compile_fail" "bad/clock_annot.ept" "-memalloc")
ADD_TEST(compile_fail_clock_causality "scripts/compile_fail" "bad/clock_causality.ept" "-memalloc")
ADD_TEST(compile_fail_clock_dep "scripts/compile_fail" "bad/clock_dep.ept" "-memalloc")
ADD_TEST(compile_fail_clocking "scripts/compile_fail" "bad/clocking.ept" "-memalloc")
ADD_TEST(compile_fail_flatten "scripts/compile_fail" "bad/flatten.ept" "-memalloc")
ADD_TEST(compile_fail_linear_acc "scripts/compile_fail" "bad/linear_acc.ept" "-memalloc")
ADD_TEST(compile_fail_linear_autom "scripts/compile_fail" "bad/linear_autom.ept" "-memalloc")
ADD_TEST(compile_fail_linear_causality "scripts/compile_fail" "bad/linear_causality.ept" "-memalloc")
ADD_TEST(compile_fail_linear_fun "scripts/compile_fail" "bad/linear_fun.ept" "-memalloc")
ADD_TEST(compile_fail_linear_init "scripts/compile_fail" "bad/linear_init.ept" "-memalloc")
ADD_TEST(compile_fail_linear_map "scripts/compile_fail" "bad/linear_map.ept" "-memalloc")
ADD_TEST(compile_fail_linear_mapfold "scripts/compile_fail" "bad/linear_mapfold.ept" "-memalloc")
ADD_TEST(compile_fail_t10-initialization "scripts/compile_fail" "bad/t10-initialization.ept" "-memalloc")
ADD_TEST(compile_fail_t11-initialization "scripts/compile_fail" "bad/t11-initialization.ept" "-memalloc")
ADD_TEST(compile_fail_t1 "scripts/compile_fail" "bad/t1.ept" "-memalloc")
ADD_TEST(compile_fail_t2 "scripts/compile_fail" "bad/t2.ept" "-memalloc")
ADD_TEST(compile_fail_t3 "scripts/compile_fail" "bad/t3.ept" "-memalloc")
ADD_TEST(compile_fail_t4 "scripts/compile_fail" "bad/t4.ept" "-memalloc")
ADD_TEST(compile_fail_t5 "scripts/compile_fail" "bad/t5.ept" "-memalloc")
ADD_TEST(compile_fail_t6 "scripts/compile_fail" "bad/t6.ept" "-memalloc")
ADD_TEST(compile_fail_t7 "scripts/compile_fail" "bad/t7.ept" "-memalloc")
ADD_TEST(compile_fail_t8-causality "scripts/compile_fail" "bad/t8-causality.ept" "-memalloc")
ADD_TEST(compile_fail_t9-initialization "scripts/compile_fail" "bad/t9-initialization.ept" "-memalloc")
ADD_TEST(compile_fail_when_merge1 "scripts/compile_fail" "bad/when_merge1.ept" "-memalloc")
ADD_TEST(compile_only_alloc "scripts/compile_only" "good/alloc.ept")
ADD_TEST(compile_only_array1 "scripts/compile_only" "good/array1.ept")
ADD_TEST(compile_only_array2 "scripts/compile_only" "good/array2.ept")
ADD_TEST(compile_only_array_fill "scripts/compile_only" "good/array_fill.ept")
ADD_TEST(compile_only_array_iterators2 "scripts/compile_only" "good/array_iterators2.ept")
ADD_TEST(compile_only_array_iterators "scripts/compile_only" "good/array_iterators.ept")
ADD_TEST(compile_only_array_power "scripts/compile_only" "good/array_power.ept")
ADD_TEST(compile_only_auto2 "scripts/compile_only" "good/auto2.ept")
ADD_TEST(compile_only_auto "scripts/compile_only" "good/auto.ept")
ADD_TEST(compile_only_autohiera2 "scripts/compile_only" "good/autohiera2.ept")
ADD_TEST(compile_only_autohiera "scripts/compile_only" "good/autohiera.ept")
ADD_TEST(compile_only_bad_updown "scripts/compile_only" "good/bad_updown.ept")
ADD_TEST(compile_only_ckannot "scripts/compile_only" "good/ckannot.ept")
ADD_TEST(compile_only_clock_causality "scripts/compile_only" "good/clock_causality.ept")
ADD_TEST(compile_only_clocks "scripts/compile_only" "good/clocks.ept")
ADD_TEST(compile_only_counter "scripts/compile_only" "good/counter.ept")
ADD_TEST(compile_only_current "scripts/compile_only" "good/current.ept")
ADD_TEST(compile_only_fbyfby2 "scripts/compile_only" "good/fbyfby2.ept")
ADD_TEST(compile_only_foldi "scripts/compile_only" "good/foldi.ept")
ADD_TEST(compile_only_format "scripts/compile_only" "good/format.ept")
ADD_TEST(compile_only_grosauto_clock "scripts/compile_only" "good/grosauto_clock.ept")
ADD_TEST(compile_only_hierarchie "scripts/compile_only" "good/hierarchie.ept")
ADD_TEST(compile_only_itfusion "scripts/compile_only" "good/itfusion.ept")
ADD_TEST(compile_only_linear_automata "scripts/compile_only" "good/linear_automata.ept")
ADD_TEST(compile_only_linear "scripts/compile_only" "good/linear.ept")
ADD_TEST(compile_only_linear_init "scripts/compile_only" "good/linear_init.ept")
ADD_TEST(compile_only_linear_split "scripts/compile_only" "good/linear_split.ept")
ADD_TEST(compile_only_linear_vars "scripts/compile_only" "good/linear_vars.ept")
ADD_TEST(compile_only_memalloc_clocks "scripts/compile_only" "good/memalloc_clocks.ept")
ADD_TEST(compile_only_memalloc_record "scripts/compile_only" "good/memalloc_record.ept")
ADD_TEST(compile_only_memalloc_simple "scripts/compile_only" "good/memalloc_simple.ept")
ADD_TEST(compile_only_name_clash "scripts/compile_only" "good/name_clash.ept")
ADD_TEST(compile_only_norm "scripts/compile_only" "good/norm.ept")
ADD_TEST(compile_only_or_keep "scripts/compile_only" "good/or_keep.ept")
ADD_TEST(compile_only_parametrize "scripts/compile_only" "good/parametrize.ept")
ADD_TEST(compile_only_pre_tuple "scripts/compile_only" "good/pre_tuple.ept")
ADD_TEST(compile_only_reinit "scripts/compile_only" "good/reinit.ept")
ADD_TEST(compile_only_sampling_stateful_output2 "scripts/compile_only" "good/sampling_stateful_output2.ept")
ADD_TEST(compile_only_sampling_stateful_output "scripts/compile_only" "good/sampling_stateful_output.ept")
ADD_TEST(compile_only_side_effet "scripts/compile_only" "good/side_effet.ept")
ADD_TEST(compile_only_statics "scripts/compile_only" "good/statics.ept")
ADD_TEST(compile_only_statics2 "scripts/compile_only" "good/statics2.ept")
ADD_TEST(compile_only_t10 "scripts/compile_only" "good/t10.ept")
ADD_TEST(compile_only_t11 "scripts/compile_only" "good/t11.ept")
ADD_TEST(compile_only_t12 "scripts/compile_only" "good/t12.ept")
ADD_TEST(compile_only_t13 "scripts/compile_only" "good/t13.ept")
ADD_TEST(compile_only_t14 "scripts/compile_only" "good/t14.ept")
ADD_TEST(compile_only_t15 "scripts/compile_only" "good/t15.ept")
ADD_TEST(compile_only_t16 "scripts/compile_only" "good/t16.ept")
ADD_TEST(compile_only_t17 "scripts/compile_only" "good/t17.ept")
ADD_TEST(compile_only_t18 "scripts/compile_only" "good/t18.ept")
ADD_TEST(compile_only_t19 "scripts/compile_only" "good/t19.ept")
ADD_TEST(compile_only_t1 "scripts/compile_only" "good/t1.ept")
ADD_TEST(compile_only_t2 "scripts/compile_only" "good/t2.ept")
ADD_TEST(compile_only_t2open "scripts/compile_only" "good/t2open.ept")
ADD_TEST(compile_only_t3 "scripts/compile_only" "good/t3.ept")
ADD_TEST(compile_only_t4 "scripts/compile_only" "good/t4.ept")
ADD_TEST(compile_only_t5 "scripts/compile_only" "good/t5.ept")
ADD_TEST(compile_only_t6 "scripts/compile_only" "good/t6.ept")
ADD_TEST(compile_only_t7 "scripts/compile_only" "good/t7.ept")
ADD_TEST(compile_only_t8 "scripts/compile_only" "good/t8.ept")
ADD_TEST(compile_only_t9 "scripts/compile_only" "good/t9.ept")
ADD_TEST(compile_only_t "scripts/compile_only" "good/t.ept")
ADD_TEST(compile_only_test "scripts/compile_only" "good/test.ept")
ADD_TEST(compile_only_threestates "scripts/compile_only" "good/threestates.ept")
ADD_TEST(compile_only_tt "scripts/compile_only" "good/tt.ept")
ADD_TEST(compile_only_tttt "scripts/compile_only" "good/tttt.ept")
ADD_TEST(compile_only_tuple_args "scripts/compile_only" "good/tuple_args.ept")
ADD_TEST(compile_only_type_alias "scripts/compile_only" "good/type_alias.ept")
ADD_TEST(compile_only_updown "scripts/compile_only" "good/updown.ept")
ADD_TEST(compile_only_when_merge1 "scripts/compile_only" "good/when_merge1.ept")
ADD_TEST(compile_gcc_run_alloc "scripts/compile_gcc_run" "good/alloc.ept")
ADD_TEST(compile_gcc_run_array1 "scripts/compile_gcc_run" "good/array1.ept")
ADD_TEST(compile_gcc_run_array2 "scripts/compile_gcc_run" "good/array2.ept")
ADD_TEST(compile_gcc_run_array_fill "scripts/compile_gcc_run" "good/array_fill.ept")
ADD_TEST(compile_gcc_run_array_iterators2 "scripts/compile_gcc_run" "good/array_iterators2.ept")
ADD_TEST(compile_gcc_run_array_iterators "scripts/compile_gcc_run" "good/array_iterators.ept")
ADD_TEST(compile_gcc_run_array_power "scripts/compile_gcc_run" "good/array_power.ept")
ADD_TEST(compile_gcc_run_auto2 "scripts/compile_gcc_run" "good/auto2.ept")
ADD_TEST(compile_gcc_run_auto "scripts/compile_gcc_run" "good/auto.ept")
ADD_TEST(compile_gcc_run_autohiera2 "scripts/compile_gcc_run" "good/autohiera2.ept")
ADD_TEST(compile_gcc_run_autohiera "scripts/compile_gcc_run" "good/autohiera.ept")
ADD_TEST(compile_gcc_run_bad_updown "scripts/compile_gcc_run" "good/bad_updown.ept")
ADD_TEST(compile_gcc_run_ckannot "scripts/compile_gcc_run" "good/ckannot.ept")
ADD_TEST(compile_gcc_run_clock_causality "scripts/compile_gcc_run" "good/clock_causality.ept")
ADD_TEST(compile_gcc_run_clocks "scripts/compile_gcc_run" "good/clocks.ept")
ADD_TEST(compile_gcc_run_counter "scripts/compile_gcc_run" "good/counter.ept")
ADD_TEST(compile_gcc_run_current "scripts/compile_gcc_run" "good/current.ept")
ADD_TEST(compile_gcc_run_fbyfby2 "scripts/compile_gcc_run" "good/fbyfby2.ept")
ADD_TEST(compile_gcc_run_foldi "scripts/compile_gcc_run" "good/foldi.ept")
ADD_TEST(compile_gcc_run_format "scripts/compile_gcc_run" "good/format.ept")
ADD_TEST(compile_gcc_run_grosauto_clock "scripts/compile_gcc_run" "good/grosauto_clock.ept")
ADD_TEST(compile_gcc_run_hierarchie "scripts/compile_gcc_run" "good/hierarchie.ept")
ADD_TEST(compile_gcc_run_itfusion "scripts/compile_gcc_run" "good/itfusion.ept")
ADD_TEST(compile_gcc_run_linear_automata "scripts/compile_gcc_run" "good/linear_automata.ept")
ADD_TEST(compile_gcc_run_linear "scripts/compile_gcc_run" "good/linear.ept")
ADD_TEST(compile_gcc_run_linear_init "scripts/compile_gcc_run" "good/linear_init.ept")
ADD_TEST(compile_gcc_run_linear_split "scripts/compile_gcc_run" "good/linear_split.ept")
ADD_TEST(compile_gcc_run_linear_vars "scripts/compile_gcc_run" "good/linear_vars.ept")
ADD_TEST(compile_gcc_run_memalloc_clocks "scripts/compile_gcc_run" "good/memalloc_clocks.ept")
ADD_TEST(compile_gcc_run_memalloc_record "scripts/compile_gcc_run" "good/memalloc_record.ept")
ADD_TEST(compile_gcc_run_memalloc_simple "scripts/compile_gcc_run" "good/memalloc_simple.ept")
ADD_TEST(compile_gcc_run_name_clash "scripts/compile_gcc_run" "good/name_clash.ept")
ADD_TEST(compile_gcc_run_norm "scripts/compile_gcc_run" "good/norm.ept")
ADD_TEST(compile_gcc_run_or_keep "scripts/compile_gcc_run" "good/or_keep.ept")
ADD_TEST(compile_gcc_run_parametrize "scripts/compile_gcc_run" "good/parametrize.ept")
ADD_TEST(compile_gcc_run_pre_tuple "scripts/compile_gcc_run" "good/pre_tuple.ept")
ADD_TEST(compile_gcc_run_reinit "scripts/compile_gcc_run" "good/reinit.ept")
ADD_TEST(compile_gcc_run_sampling_stateful_output2 "scripts/compile_gcc_run" "good/sampling_stateful_output2.ept")
ADD_TEST(compile_gcc_run_sampling_stateful_output "scripts/compile_gcc_run" "good/sampling_stateful_output.ept")
ADD_TEST(compile_gcc_run_side_effet "scripts/compile_gcc_run" "good/side_effet.ept")
ADD_TEST(compile_gcc_run_statics "scripts/compile_gcc_run" "good/statics.ept")
ADD_TEST(compile_gcc_run_statics2 "scripts/compile_gcc_run" "good/statics2.ept")
ADD_TEST(compile_gcc_run_t10 "scripts/compile_gcc_run" "good/t10.ept")
ADD_TEST(compile_gcc_run_t11 "scripts/compile_gcc_run" "good/t11.ept")
ADD_TEST(compile_gcc_run_t12 "scripts/compile_gcc_run" "good/t12.ept")
ADD_TEST(compile_gcc_run_t13 "scripts/compile_gcc_run" "good/t13.ept")
ADD_TEST(compile_gcc_run_t14 "scripts/compile_gcc_run" "good/t14.ept")
ADD_TEST(compile_gcc_run_t15 "scripts/compile_gcc_run" "good/t15.ept")
ADD_TEST(compile_gcc_run_t16 "scripts/compile_gcc_run" "good/t16.ept")
ADD_TEST(compile_gcc_run_t17 "scripts/compile_gcc_run" "good/t17.ept")
ADD_TEST(compile_gcc_run_t18 "scripts/compile_gcc_run" "good/t18.ept")
ADD_TEST(compile_gcc_run_t19 "scripts/compile_gcc_run" "good/t19.ept")
ADD_TEST(compile_gcc_run_t1 "scripts/compile_gcc_run" "good/t1.ept")
ADD_TEST(compile_gcc_run_t2 "scripts/compile_gcc_run" "good/t2.ept")
ADD_TEST(compile_gcc_run_t2open "scripts/compile_gcc_run" "good/t2open.ept")
ADD_TEST(compile_gcc_run_t3 "scripts/compile_gcc_run" "good/t3.ept")
ADD_TEST(compile_gcc_run_t4 "scripts/compile_gcc_run" "good/t4.ept")
ADD_TEST(compile_gcc_run_t5 "scripts/compile_gcc_run" "good/t5.ept")
ADD_TEST(compile_gcc_run_t6 "scripts/compile_gcc_run" "good/t6.ept")
ADD_TEST(compile_gcc_run_t7 "scripts/compile_gcc_run" "good/t7.ept")
ADD_TEST(compile_gcc_run_t8 "scripts/compile_gcc_run" "good/t8.ept")
ADD_TEST(compile_gcc_run_t9 "scripts/compile_gcc_run" "good/t9.ept")
ADD_TEST(compile_gcc_run_t "scripts/compile_gcc_run" "good/t.ept")
ADD_TEST(compile_gcc_run_test "scripts/compile_gcc_run" "good/test.ept")
ADD_TEST(compile_gcc_run_threestates "scripts/compile_gcc_run" "good/threestates.ept")
ADD_TEST(compile_gcc_run_tt "scripts/compile_gcc_run" "good/tt.ept")
ADD_TEST(compile_gcc_run_tttt "scripts/compile_gcc_run" "good/tttt.ept")
ADD_TEST(compile_gcc_run_tuple_args "scripts/compile_gcc_run" "good/tuple_args.ept")
ADD_TEST(compile_gcc_run_type_alias "scripts/compile_gcc_run" "good/type_alias.ept")
ADD_TEST(compile_gcc_run_updown "scripts/compile_gcc_run" "good/updown.ept")
ADD_TEST(compile_gcc_run_when_merge1 "scripts/compile_gcc_run" "good/when_merge1.ept")

