#!/bin/bash

for i in bad/*.ept; do
    echo 'ADD_TEST(compile_fail_'`basename $i .ept` '"scripts/compile_fail"' '"'$i'" "-memalloc")'
done

for i in good/*.ept; do
    echo 'ADD_TEST(compile_only_'`basename $i .ept` '"scripts/compile_only"' '"'$i'")'
done

for i in good/*.ept; do
    echo 'ADD_TEST(compile_gcc_run_'`basename $i .ept` '"scripts/compile_gcc_run"' '"'$i'")'
done


